import * as THREE from 'three';
import {clone} from 'three/examples/jsm/utils/SkeletonUtils.js';
import {AssetLoader} from './assets/AssetLoader';import {musicAsset} from './assets/assetManifest';import {CampWorld} from './world/CampWorld';import {PlayerController} from './player/PlayerController';import {NpcManager} from './npc/NpcManager';import {EffectManager,EffectId,VisualSettings,defaultVisualSettings} from './effects/EffectManager';import {InteractionManager} from './interactions/InteractionManager';import {SpeakerAudio} from './audio/SpeakerAudio';import {itemById} from './interactions/itemConfig';
const qs=<T extends HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
export class Game{
 canvas=qs<HTMLCanvasElement>('#game');renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(65,1,.1,100);clock=new THREE.Clock();player!:PlayerController;world!:CampWorld;npcs!:NpcManager;effects!:EffectManager;interactions!:InteractionManager;paused=false;toiletTimer=0;private settings:VisualSettings;private propModels=new Map<string,THREE.Object3D>();private inspectRenderer?:THREE.WebGLRenderer;private inspectScene?:THREE.Scene;private inspectCamera?:THREE.PerspectiveCamera;private inspectModel?:THREE.Object3D;
 speakerAudio=new SpeakerAudio(musicAsset);
 constructor(){try{this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true})}catch{qs('#load-error').textContent='Ta przeglądarka nie obsługuje WebGL.';qs('#loading').hidden=false;throw new Error('WebGL unavailable')}this.settings={...defaultVisualSettings,...JSON.parse(localStorage.getItem('camp-visual-settings')||'{}')};this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.scene.background=new THREE.Color(0x9bb9d0);this.scene.fog=new THREE.Fog(0x9bb9d0,24,58);addEventListener('resize',()=>this.resize());addEventListener('keydown',e=>this.key(e));document.addEventListener('pointerlockchange',()=>{const modal=!qs('#dialog').hidden||!qs('#inventory').hidden||!qs('#inspect').hidden;if(!modal&&!this.toiletTimer&&document.pointerLockElement!==this.canvas&&this.player?.enabled)this.setPause(true)});this.syncSettingsUi()}
 async start(){const loading=qs('#loading'),text=qs('#load-text'),error=qs('#load-error');loading.hidden=false;try{const loader=new AssetLoader(m=>text.textContent=m,m=>{error.textContent=m;error.hidden=false});const assets=await loader.loadAll();assets.interactables.forEach((asset,id)=>this.propModels.set(id,asset.scene));this.world=new CampWorld(this.scene,assets);this.npcs=new NpcManager(this.scene,assets.characters,assets.speaker,(x,z)=>this.world.canMove(x,z));this.player=new PlayerController(this.camera,this.canvas,(x,z)=>this.world.canMove(x,z));this.effects=new EffectManager(this.renderer,this.scene,this.camera);this.effects.setSettings(this.settings);this.interactions=new InteractionManager(this.camera,()=>[...this.npcs.npcs.map(n=>n.root),...this.world.interactables.map(i=>i.object)]);this.player.enabled=true;loading.hidden=true;qs('#hud').hidden=false;this.loop()}catch(e){error.textContent=`Nie udało się uruchomić gry: ${String(e)}`;error.hidden=false}}
 key(event:KeyboardEvent){if(!this.player)return;if(event.key==='Escape'&&!qs('#inspect').hidden){event.preventDefault();this.closeInspect();return}if(event.key==='Tab'){event.preventDefault();this.toggleInventory()}if(event.key.toLowerCase()==='e')this.interact();if(event.key==='Escape'&&document.pointerLockElement===this.canvas){document.exitPointerLock();this.setPause(true)}}
 interact(){if(this.paused)return;if(this.toiletTimer){this.toiletTimer=0;qs('#fade').classList.remove('show');this.player.enabled=true;this.canvas.requestPointerLock();return}const interaction=this.interactions.current;if(!interaction)return;if(interaction.kind==='speaker'){this.speakerAudio.toggle().then(playing=>this.toast(playing?'Głośnik: muzyka włączona':'Głośnik: muzyka wyłączona'));return}if(interaction.kind==='toilet'){this.toiletTimer=2;this.player.enabled=false;qs('#fade').classList.add('show');this.toast('Chwila prywatności…');return}if(interaction.kind==='item'){this.inspect(interaction.itemId);return}if(interaction.kind==='npc'){const npc=this.npcs.npcs.find(n=>n.name===interaction.name);if(npc){qs('#dialog-name').textContent=npc.name;qs('#dialog-text').textContent=npc.line[Math.floor(Math.random()*npc.line.length)];qs('#dialog').hidden=false;this.player.enabled=false;document.exitPointerLock()}}}
 private inspect(id:string){const item=itemById.get(id as 'joint'|'cocaine'|'mdma'|'mushrooms'|'lsd');if(!item)return;qs('#inspect-name').textContent=item.label;qs('#inspect-text').textContent=item.description;qs('#inspect-help').textContent='E — uruchom efekt w grze · Esc — wróć do obozu';qs('#inspect').hidden=false;this.player.enabled=false;document.exitPointerLock();this.createInspectScene(id)}
 private createInspectScene(id:string){const canvas=qs<HTMLCanvasElement>('#inspect-canvas');this.inspectRenderer?.dispose();this.inspectRenderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});this.inspectRenderer.setPixelRatio(Math.min(devicePixelRatio,2));this.inspectRenderer.setSize(360,280,false);this.inspectScene=new THREE.Scene();this.inspectScene.background=new THREE.Color(0x09070f);this.inspectCamera=new THREE.PerspectiveCamera(35,360/280,.01,100);this.inspectCamera.position.set(0,.3,2.8);this.inspectScene.add(new THREE.HemisphereLight(0xbdd8ff,0x241630,2.2));const light=new THREE.DirectionalLight(0xffffff,2.5);light.position.set(2,3,3);this.inspectScene.add(light);const source=this.propModels.get(id);this.inspectModel=source?clone(source):new THREE.Mesh(new THREE.IcosahedronGeometry(.5),new THREE.MeshStandardMaterial({color:0xa8e04a}));const box=new THREE.Box3().setFromObject(this.inspectModel),size=box.getSize(new THREE.Vector3()).length();this.inspectModel.scale.setScalar(1.4/Math.max(.01,size));box.setFromObject(this.inspectModel);this.inspectModel.position.y=-(box.min.y+box.max.y)/2;this.inspectScene.add(this.inspectModel)}
 closeInspect(){qs('#inspect').hidden=true;this.player.enabled=true;this.canvas.requestPointerLock()}
 acceptInspect(){const id=[...itemById.entries()].find(([,item])=>item.label===qs('#inspect-name').textContent)?.[0];if(id){const item=itemById.get(id)!;this.closeInspect();this.useEffect(item.effect)}}
 toggleInventory(){const inventory=qs('#inventory');if(this.paused)return;inventory.hidden=!inventory.hidden;this.player.enabled=inventory.hidden;if(inventory.hidden)this.canvas.requestPointerLock();else document.exitPointerLock()}
 useEffect(id:EffectId){if((id==='Grzyb'||id==='MDMA'||id==='LSD')&&!localStorage.getItem('camp-effect-warning')){const proceed=window.confirm('Ten fikcyjny efekt zawiera intensywne ruchy obrazu i światło. Kontynuować?');localStorage.setItem('camp-effect-warning','1');if(!proceed)return}this.effects.use(id);qs('#inventory').hidden=true;this.player.enabled=true;this.canvas.requestPointerLock();this.toast(`${id}: efekt uruchomiony`)}
 cancelEffect(){this.effects.cancel();this.toast('Efekt wygaszany')}closeDialog(){qs('#dialog').hidden=true;this.player.enabled=true;this.canvas.requestPointerLock()}setPause(on:boolean){this.paused=on;qs('#pause').hidden=!on;this.player.enabled=!on;if(!on)this.canvas.requestPointerLock()}
 updateSettings(values:Partial<VisualSettings>){Object.assign(this.settings,values);localStorage.setItem('camp-visual-settings',JSON.stringify(this.settings));this.effects?.setSettings(values);this.syncSettingsUi()}
 private syncSettingsUi(){const set=(id:string,value:boolean|number)=>{const input=qs<HTMLInputElement>(id);if(input.type==='range')input.value=String(Number(value)*100);else input.checked=Boolean(value)};set('#setting-intensity',this.settings.intensity);set('#setting-reduce-motion',this.settings.reduceMotion);set('#setting-limit-sway',this.settings.limitSway);set('#setting-disable-shake',this.settings.disableShake);set('#setting-disable-bloom',this.settings.disableBloom)}
 private loop=()=>{requestAnimationFrame(this.loop);const dt=Math.min(this.clock.getDelta(),.05);if(this.toiletTimer){this.toiletTimer-=dt;if(this.toiletTimer<=0){this.toiletTimer=0;qs('#fade').classList.remove('show');this.player.enabled=true;this.canvas.requestPointerLock();this.toast('Gotowe.')}}this.player.update(dt,this.effects.modifiers);this.npcs.update(dt,this.clock.elapsedTime);const interaction=this.interactions.update(),prompt=qs('#prompt');if(interaction){prompt.textContent=interaction.kind==='npc'?`E — Porozmawiaj z ${interaction.name}`:interaction.kind==='speaker'?'E — Włącz / wyłącz muzykę':interaction.kind==='item'?`E — ${itemById.get(interaction.itemId)?.label||'Obejrzyj przedmiot'}`:'E — Wejdź do toi-toia';prompt.hidden=false}else prompt.hidden=true;this.world.update(this.clock.elapsedTime);this.effects.update(dt);this.effects.render();if(!qs('#inspect').hidden&&this.inspectRenderer&&this.inspectScene&&this.inspectCamera){if(this.inspectModel)this.inspectModel.rotation.y+=dt*.75;this.inspectRenderer.render(this.inspectScene,this.inspectCamera)}const active=this.effects.active;qs('#effect-hud').textContent=active?`${active} · ${this.effects.phase} · ${Math.ceil(this.effects.remaining)} s`:'Brak aktywnego efektu';qs('#smoke').hidden=this.effects.active!=='Papieros'}
 resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);this.effects?.resize(innerWidth,innerHeight)}toast(message:string){const toast=qs('#toast');toast.textContent=message;toast.classList.add('visible');window.setTimeout(()=>toast.classList.remove('visible'),2200)}
}
