import * as THREE from 'three';import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';import {clone} from 'three/examples/jsm/utils/SkeletonUtils.js';import {characterAssets} from '../assets/assetManifest';import {disposeObjectTree} from '../lifecycle/disposeThree';
type Cached={scene:THREE.Object3D;animations:THREE.AnimationClip[]};
/** Transparent start-screen model layer. Its orthographic camera is refit from the complete model bounds on every resize. */
export class CharacterPreview{private renderer:THREE.WebGLRenderer;private scene=new THREE.Scene();private camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,100);private current?:THREE.Object3D;private mixer?:THREE.AnimationMixer;private cache=new Map<string,Cached>();private token=0;private clock=new THREE.Clock();private frame=0;private observer:ResizeObserver;private bounds?:THREE.Box3;private disposed=false;
 constructor(private layer:HTMLElement){const canvas=document.createElement('canvas');layer.append(canvas);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});this.renderer.setClearColor(0x000000,0);this.renderer.setClearAlpha(0);this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.scene.background=null;this.camera.position.z=10;this.scene.add(new THREE.HemisphereLight(0xd9ecff,0x25152f,2.7));const key=new THREE.DirectionalLight(0xffffff,2.6);key.position.set(2,4,4);this.scene.add(key);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(layer);this.resize();this.draw()}
 async show(name:string){const asset=characterAssets.find(x=>x.name===name);if(!asset||this.disposed)return;const token=++this.token,key=`${asset.id}:${asset.previewUrl||asset.url}`;try{let source=this.cache.get(key);if(!source){const gltf=await new GLTFLoader().loadAsync(asset.previewUrl||asset.url);source={scene:gltf.scene,animations:gltf.animations};if(this.disposed||token!==this.token){disposeObjectTree(source.scene);return}this.cache.set(key,source)}if(this.disposed||token!==this.token)return;if(this.current)this.scene.remove(this.current);this.mixer?.stopAllAction();const model=clone(source.scene);model.position.set(0,0,0);this.bounds=new THREE.Box3().setFromObject(model);this.current=model;this.fitToLayer();this.mixer=new THREE.AnimationMixer(model);const idle=source.animations.find(clip=>clip.name==='Idle')||source.animations[0];if(idle)this.mixer.clipAction(idle).reset().play();this.scene.add(model)}catch(error){if(!this.disposed&&token===this.token)console.error(`Nie udało się załadować podglądu ${name}`,error)}}
 private fitToLayer(){if(!this.current||!this.bounds)return;const w=Math.max(1,this.layer.clientWidth),h=Math.max(1,this.layer.clientHeight),aspect=w/h,size=this.bounds.getSize(new THREE.Vector3()),center=this.bounds.getCenter(new THREE.Vector3());const padding=.14;const halfHeight=Math.max(size.y/(2*(1-padding)),size.x/(2*aspect*(1-padding)));const halfWidth=halfHeight*aspect;this.camera.left=-halfWidth;this.camera.right=halfWidth;this.camera.top=halfHeight;this.camera.bottom=-halfHeight;this.camera.position.set(0,center.y,10);this.camera.updateProjectionMatrix();const margin=Math.max(size.x,size.y)*.07;const targetX=w>=900?halfWidth-size.x*.5-margin:0;this.current.position.set(targetX-center.x,0,0);const check=new THREE.Box3().setFromObject(this.current),visible=check.min.y>=this.camera.bottom&&check.max.y<=this.camera.top&&check.min.x>=this.camera.left&&check.max.x<=this.camera.right;if(!visible){console.warn('CharacterPreview: refitting model bounds');this.camera.top=halfHeight*1.08;this.camera.bottom=-halfHeight*1.08;this.camera.left=-halfWidth*1.08;this.camera.right=halfWidth*1.08;this.camera.updateProjectionMatrix()}}
 private resize(){const r=this.layer.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);this.renderer.setSize(w,h,false);this.fitToLayer()}
 private draw=()=>{if(this.disposed)return;this.frame=requestAnimationFrame(this.draw);this.mixer?.update(Math.min(this.clock.getDelta(),.05));this.renderer.render(this.scene,this.camera)};dispose(){if(this.disposed)return;this.disposed=true;this.token++;cancelAnimationFrame(this.frame);this.observer.disconnect();this.mixer?.stopAllAction();this.cache.forEach(source=>disposeObjectTree(source.scene));this.cache.clear();this.scene.clear();this.renderer.dispose();this.layer.replaceChildren()}}
