import * as THREE from 'three';
import {EffectComposer} from 'three/examples/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/examples/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import {AfterimagePass} from 'three/examples/jsm/postprocessing/AfterimagePass.js';
import {ShaderPass} from 'three/examples/jsm/postprocessing/ShaderPass.js';
export type EffectId='Piwo'|'Papieros'|'Joint'|'Kreska'|'Grzyb'|'MDMA'|'LSD';export type EffectPhase='inactive'|'fadeIn'|'active'|'fadeOut';export type VisualSettings={intensity:number;reduceMotion:boolean;limitSway:boolean;disableShake:boolean;disableBloom:boolean};
export const defaultVisualSettings:VisualSettings={intensity:1,reduceMotion:false,limitSway:false,disableShake:false,disableBloom:false};
type Config={fadeIn:number;active:number;fadeOut:number;speed:number;fov:number;bloom:number;saturation:number;warp:number;afterimage:number;sway:number;shake:number;bob:number;hue:number;chroma:number;contrast:number;brightness:number;vignette:number;blur:number;pulse:number};
const configs:Record<EffectId,Config>={
 Piwo:{fadeIn:1,active:18,fadeOut:2,speed:.85,fov:65,bloom:.08,saturation:.94,warp:.22,afterimage:.72,sway:.20,shake:0,bob:.9,hue:.01,chroma:.008,contrast:.9,brightness:-.02,vignette:.46,blur:.20,pulse:.55},
 Papieros:{fadeIn:.5,active:12,fadeOut:1,speed:1,fov:65,bloom:.05,saturation:.9,warp:.04,afterimage:0,sway:.08,shake:0,bob:.85,hue:.015,chroma:.002,contrast:.94,brightness:.025,vignette:.12,blur:.04,pulse:.35},
 Joint:{fadeIn:1,active:22,fadeOut:3,speed:.78,fov:66.4,bloom:.25,saturation:1.22,warp:.18,afterimage:.88,sway:.09,shake:0,bob:.8,hue:.045,chroma:.006,contrast:1.02,brightness:.035,vignette:.28,blur:.08,pulse:.22},
 Kreska:{fadeIn:.7,active:13,fadeOut:2,speed:1.45,fov:76,bloom:.20,saturation:1.1,warp:.04,afterimage:0,sway:0,shake:.30,bob:1.45,hue:-.025,chroma:.004,contrast:1.32,brightness:.055,vignette:.48,blur:0,pulse:2.6},
 Grzyb:{fadeIn:2,active:25,fadeOut:4,speed:.9,fov:69,bloom:.28,saturation:1.38,warp:.80,afterimage:.20,sway:.12,shake:0,bob:1,hue:.10,chroma:.012,contrast:1.05,brightness:.02,vignette:.30,blur:.07,pulse:.42},
 MDMA:{fadeIn:1.5,active:22,fadeOut:3,speed:1,fov:66,bloom:1.35,saturation:1.58,warp:.08,afterimage:.1,sway:.08,shake:0,bob:1,hue:.06,chroma:.004,contrast:1.08,brightness:.10,vignette:.16,blur:.05,pulse:1.1},
 LSD:{fadeIn:1.5,active:25,fadeOut:3,speed:.92,fov:71,bloom:.68,saturation:1.72,warp:1.08,afterimage:.60,sway:.13,shake:0,bob:1.08,hue:.34,chroma:.026,contrast:1.20,brightness:.04,vignette:.38,blur:.025,pulse:.78}
};
const shader={uniforms:{tDiffuse:{value:null},time:{value:0},distortion:{value:0},saturation:{value:1},hue:{value:0},chroma:{value:0},contrast:{value:1},brightness:{value:0},vignette:{value:0},blur:{value:0},pulse:{value:0}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D tDiffuse;uniform float time,distortion,saturation,hue,chroma,contrast,brightness,vignette,blur,pulse;varying vec2 vUv;
vec3 hueShift(vec3 c,float a){float s=sin(a),co=cos(a);mat3 m=mat3(.299+.701*co,.587-.587*co,.114-.114*co,.299-.299*co,.587+.413*co,.114+.886*co,.299-.3*co,.587-.588*co,.114+.886*co);return clamp(m*c,0.,1.);}void main(){vec2 uv=vUv-.5;float r=length(uv);float wave=sin(uv.y*14.+time*.75)+cos(uv.x*12.-time*.53);uv*=1.+distortion*(.015+.022*sin(time*pulse))*r*r;uv+=normalize(uv+vec2(.0001))*wave*distortion*.004;uv+=.5;float ca=chroma*(.25+r*.9);vec2 d=normalize(uv-.5+vec2(.0001))*ca;vec3 col;col.r=texture2D(tDiffuse,uv+d).r;col.g=texture2D(tDiffuse,uv).g;col.b=texture2D(tDiffuse,uv-d).b;if(blur>0.){col+=texture2D(tDiffuse,uv+vec2(blur*.003,0.)).rgb;col+=texture2D(tDiffuse,uv-vec2(blur*.003,0.)).rgb;col/=3.;}float l=dot(col,vec3(.299,.587,.114));col=mix(vec3(l),col,saturation);col=hueShift(col,hue*sin(time*.22+wave*.12));col=(col-.5)*contrast+.5+brightness;col*=1.-smoothstep(.15,.72,r)*vignette;gl_FragColor=vec4(clamp(col,0.,1.),1.);}`};
export class EffectManager{composer:EffectComposer;bloom:UnrealBloomPass;afterimage:AfterimagePass;shader:ShaderPass;active:EffectId|null=null;phase:EffectPhase='inactive';remaining=0;private elapsed=0;private intensity=0;settings:VisualSettings={...defaultVisualSettings};constructor(renderer:THREE.WebGLRenderer,scene:THREE.Scene,private camera:THREE.PerspectiveCamera){this.composer=new EffectComposer(renderer);this.composer.addPass(new RenderPass(scene,camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),0,.3,.8);this.composer.addPass(this.bloom);this.afterimage=new AfterimagePass(.88);this.afterimage.enabled=false;this.composer.addPass(this.afterimage);this.shader=new ShaderPass(shader);this.composer.addPass(this.shader)}
 use(id:EffectId){if(this.active&&this.active!==id)this.afterimage.uniforms.damp.value=0;this.active=id;this.phase='fadeIn';this.elapsed=0;this.remaining=configs[id].active;this.intensity=0}
 cancel(){if(this.active&&this.phase!=='fadeOut'){this.phase='fadeOut';this.elapsed=0}}
 setSettings(settings:Partial<VisualSettings>){Object.assign(this.settings,settings)}
 update(dt:number){if(this.active){const c=configs[this.active];this.elapsed+=dt;if(this.phase==='fadeIn'){this.intensity=Math.min(1,this.elapsed/c.fadeIn);if(this.intensity>=1){this.phase='active';this.elapsed=0}}else if(this.phase==='active'){this.remaining=Math.max(0,c.active-this.elapsed);this.intensity=1;if(this.elapsed>=c.active){this.phase='fadeOut';this.elapsed=0}}else{this.intensity=Math.max(0,1-this.elapsed/c.fadeOut);if(this.intensity<=0){this.active=null;this.phase='inactive';this.remaining=0;this.afterimage.uniforms.damp.value=0}}}const c=this.active?configs[this.active]:null,level=this.intensity*this.settings.intensity,pulse=c?1+Math.sin(this.shader.uniforms.time.value*c.pulse)*.08*level:1;this.bloom.enabled=!this.settings.disableBloom&&!!c&&c.bloom>0;this.bloom.strength=(c?.bloom||0)*level*pulse;this.afterimage.enabled=!!c&&c.afterimage>0&&level>.02;this.afterimage.uniforms.damp.value=c?.afterimage||0;const u=this.shader.uniforms;u.distortion.value=(this.settings.reduceMotion?0:c?.warp||0)*level;u.saturation.value=THREE.MathUtils.lerp(1,c?.saturation||1,level);u.hue.value=(c?.hue||0)*level;u.chroma.value=(c?.chroma||0)*level;u.contrast.value=THREE.MathUtils.lerp(1,c?.contrast||1,level);u.brightness.value=(c?.brightness||0)*level;u.vignette.value=(c?.vignette||0)*level;u.blur.value=(c?.blur||0)*level;u.pulse.value=c?.pulse||0;u.time.value+=dt;const target=c?THREE.MathUtils.lerp(65,c.fov,level)*(1+Math.sin(u.time.value*(c.pulse||.2))*.004*level):65;this.camera.fov=THREE.MathUtils.damp(this.camera.fov,target,6,dt);this.camera.updateProjectionMatrix()}
 get modifiers(){const c=this.active?configs[this.active]:null,level=this.intensity*this.settings.intensity;return {speed:THREE.MathUtils.lerp(1,c?.speed||1,level),sway:this.settings.reduceMotion||this.settings.limitSway?0:(c?.sway||0)*level,shake:this.settings.reduceMotion||this.settings.disableShake?0:(c?.shake||0)*level,bob:THREE.MathUtils.lerp(1,c?.bob||1,level)}}
 render(){this.composer.render()}resize(w:number,h:number){this.composer.setSize(w,h)}
 dispose(){this.active=null;this.phase='inactive';this.afterimage.enabled=false;this.composer.dispose()}
}
