import * as THREE from 'three';
import {Sky} from 'three/examples/jsm/objects/Sky.js';
import {GLTF} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {clone} from 'three/examples/jsm/utils/SkeletonUtils.js';
import {Grass} from './vendor/three-stylized/index';
import {addHorizonSkybox} from './HorizonSkybox';
import {inspectableItems} from '../interactions/itemConfig';
const WORLD_SIZE=117.6, WORLD_LIMIT=WORLD_SIZE/2;
export type WorldObject={object:THREE.Object3D;label:string;action:'toilet'|'item'};
const simpleMaterial=(color:number)=>new THREE.MeshStandardMaterial({color,roughness:.78});
function terrain(){const g=new THREE.PlaneGeometry(WORLD_SIZE,WORLD_SIZE,96,96).rotateX(-Math.PI/2),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);p.setY(i,.18*Math.sin(x*.065)*Math.cos(z*.055)+.09*Math.sin(x*.19+z*.13))}p.needsUpdate=true;g.computeVertexNormals();return g}
export class CampWorld{
 colliders:({x:number;z:number;r:number}|{box:THREE.Box3})[]=[];interactables:WorldObject[]=[];private grass:Grass;
 constructor(scene:THREE.Scene,models:{largeTent:GLTF|null;smallTent:GLTF|null;flag:GLTF|null;interactables:Map<string,GLTF>}){
  const sky=new Sky();sky.scale.setScalar(450000);sky.visible=false;scene.add(sky);addHorizonSkybox(scene);
  scene.add(new THREE.HemisphereLight(0xb9dcff,0x4b3c23,1.7));const sun=new THREE.DirectionalLight(0xffe0b0,3.2);sun.position.set(-10,17,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=22;sun.shadow.camera.bottom=-22;scene.add(sun);
  const ground=new THREE.Mesh(terrain(),simpleMaterial(0x56732d));ground.receiveShadow=true;ground.userData.excludeMushroomWireframe=true;scene.add(ground);
  this.grass=new Grass({surface:ground,grass:{density:17,brightness:.38,blade:{minHeight:.18,maxHeight:.58,minWidth:.025,maxWidth:.085,segments:4},colors:{bottom:'#52632b',top:'#b0a35b',backlight:'#d2c878',ground:'#56732d'},wind:{strength:.16,speed:.85,frequency:.55,turbulence:.22,lean:.025,direction:32},lighting:{direction:sun.position.clone().normalize(),color:'#ffe0b0',intensity:1.1},shadow:false},wildflowers:{enabled:false}});this.grass.userData.excludeMushroomWireframe=true;this.grass.syncDirectionalLight(sun);scene.add(this.grass);
  this.tarp(scene);this.placeTent(scene,models.largeTent,new THREE.Vector3(-8,0,-5),3.2,3.1);[[-8,3,.4],[-2,7,.1],[5,6,-.5],[8,2,.4],[7,-5,0],[-3,-7,.7]].forEach(([x,z,r])=>this.placeTent(scene,models.smallTent,new THREE.Vector3(x,0,z),1.8,1.7,r));this.toilet(scene);this.mast(scene,models.flag);this.table(scene,models.interactables);
 }
 private prepare(model:GLTF|null,height:number,color:number){if(!model)return new THREE.Mesh(new THREE.ConeGeometry(1.7,1.7,4),simpleMaterial(color));const root=clone(model.scene),box=new THREE.Box3().setFromObject(root);root.scale.setScalar(height/Math.max(.01,box.max.y-box.min.y));box.setFromObject(root);root.position.y=-box.min.y;root.traverse(o=>{const m=o as THREE.Mesh;if(m.isMesh){m.castShadow=true;m.receiveShadow=true}});return root}
 private placeTent(scene:THREE.Scene,source:GLTF|null,position:THREE.Vector3,height:number,radius:number,rotation=0){const object=this.prepare(source,height,0x5c8dbe);object.position.add(position);object.rotation.y=rotation;scene.add(object);scene.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(object);box.min.y=-2;box.max.y=4;this.colliders.push({box})}
 private tarp(scene:THREE.Scene){const tarp=new THREE.Mesh(new THREE.PlaneGeometry(8,6,8,6),simpleMaterial(0x111119));tarp.rotation.x=-Math.PI/2;tarp.position.y=3.15;tarp.castShadow=true;scene.add(tarp);[[-4,-3],[4,-3],[-4,3],[4,3]].forEach(([x,z])=>{const pole=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,3.2,8),simpleMaterial(0x3d3d41));pole.position.set(x,1.6,z);scene.add(pole);this.colliders.push({x,z,r:.25})})}
 private toilet(scene:THREE.Scene){const toilet=new THREE.Group(),cabin=new THREE.Mesh(new THREE.BoxGeometry(1.5,2.5,1.5),simpleMaterial(0x356ddb));cabin.position.y=1.25;toilet.add(cabin);toilet.position.set(-12,0,10);toilet.userData.interaction={kind:'toilet'};toilet.traverse(o=>o.userData.interactionRoot=toilet);scene.add(toilet);this.colliders.push({x:-12,z:10,r:1.25});this.interactables.push({object:toilet,label:'Wejdź do toi-toia',action:'toilet'})}
 private mast(scene:THREE.Scene,source:GLTF|null){const mast=this.prepare(source,5.8,0x303035);mast.position.set(0,0,13);scene.add(mast);this.colliders.push({x:0,z:13,r:.4})}
 private table(scene:THREE.Scene,models:Map<string,GLTF>){const table=models.get('table')?clone(models.get('table')!.scene):new THREE.Mesh(new THREE.BoxGeometry(2.4,.16,1.2),simpleMaterial(0x73451f));let box=new THREE.Box3().setFromObject(table);table.scale.setScalar(1.12/Math.max(.01,box.max.y-box.min.y));box.setFromObject(table);table.position.set(3,-box.min.y,4);table.rotation.y=-.5;scene.add(table);this.colliders.push({x:3,z:4,r:1.35});inspectableItems.forEach((item,i)=>{const source=models.get(item.id),o=source?clone(source.scene):new THREE.Mesh(new THREE.IcosahedronGeometry(.11),simpleMaterial(0xa8e04a));box=new THREE.Box3().setFromObject(o);o.scale.setScalar(.24/Math.max(.01,box.max.y-box.min.y));box.setFromObject(o);o.position.set(2.25+i*.37,1.17-box.min.y,3.7+(i%2)*.28);o.rotation.y=i*.8;o.userData.interaction={kind:'item',itemId:item.id};const hitbox=new THREE.Mesh(new THREE.SphereGeometry(.36,10,8),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));hitbox.name=`InteractionHitbox_${item.id}`;o.add(hitbox);o.traverse(x=>x.userData.interactionRoot=o);scene.add(o);this.interactables.push({object:o,label:`Obejrzyj: ${item.label}`,action:'item'})})}
 canMove(x:number,z:number){const r=.34;return x>-WORLD_LIMIT+r&&x<WORLD_LIMIT-r&&z>-WORLD_LIMIT+r&&z<WORLD_LIMIT-r&&!this.colliders.some(c=>'box'in c?x>c.box.min.x-r&&x<c.box.max.x+r&&z>c.box.min.z-r&&z<c.box.max.z+r:Math.hypot(x-c.x,z-c.z)<c.r+r)}
 update(time:number){this.grass.update(time)}
 dispose(){this.grass.dispose();this.colliders.length=0;this.interactables.length=0}
}
